// Intel Terminal — Markdown report generator
// Produces a clean, LLM-friendly markdown summary of the latest sweep.
// Used by /report.md (live), /llms-full.txt (discovery+report) and as the
// canonical source for the Telegram daily briefing.
// Pure function: takes the synthesized sweep data, returns markdown.

const NFA = '> ⚠️ **Not Financial Advice (NFA).** All trade ideas and signal-based observations are generated by an AI model from publicly available OSINT data. They are informational only — not a recommendation to buy or sell any security, not investment advice, and not a solicitation of any kind. Do your own research and consult a licensed financial advisor. Past performance does not guarantee future results.';

function esc(s) {
  return String(s ?? '')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function fmtUTC(iso) {
  if (!iso) return 'n/a';
  const d = new Date(iso);
  if (isNaN(d)) return String(iso);
  return d.toISOString().replace('T', ' ').slice(0, 19) + 'Z';
}

function fmtUTC7(iso) {
  if (!iso) return 'n/a';
  const d = new Date(iso);
  if (isNaN(d)) return String(iso);
  const shifted = new Date(d.getTime() + 7 * 3600 * 1000);
  return shifted.toISOString().replace('T', ' ').slice(0, 19) + ' (UTC+7)';
}

function deltaSection(D) {
  const s = D.delta?.summary;
  if (!s) return '';
  const dir = (s.direction || 'neutral').toUpperCase();
  const out = [`**Delta:** ${dir} — ${s.totalChanges ?? 0} changes, ${s.criticalChanges ?? 0} critical.`];
  const signals = D.delta?.signals || {};
  const entries = [];
  (signals.new || []).forEach(x => entries.push(['NEW', x.label || x.key || (x.text ? x.text.slice(0, 100) : ''), x.from ?? x.value, x.to ?? '', x.reason]));
  (signals.escalated || []).forEach(x => entries.push(['ESCALATED', x.label || x.key, x.from, x.to]));
  (signals.deescalated || []).forEach(x => entries.push(['DE-ESCALATED', x.label || x.key, x.from, x.to]));
  if (entries.length) {
    out.push('');
    entries.forEach(([kind, label, from, to, reason]) => {
      const val = (from != null && to !== '') ? ` ${from} → ${to}` : '';
      const why = reason ? ` — ${esc(reason)}` : '';
      out.push(`- **${kind}:** ${esc(label)}${val}${why}`);
    });
  }
  return out.join('\n');
}

function ideasSection(D) {
  const ideas = Array.isArray(D.ideas) ? D.ideas : [];
  if (!ideas.length) {
    const src = D.ideasSource || 'unknown';
    if (src === 'llm-failed') return '**AI Trade Ideas:** Generation failed this sweep (LLM error).';
    if (src === 'llm') return '**AI Trade Ideas:** LLM returned no ideas this sweep.';
    return '**AI Trade Ideas:** Not available (LLM not configured).';
  }
  const out = ['## AI Trade Ideas', ''];
  ideas.forEach((i, idx) => {
    out.push(`### ${idx + 1}. ${i.type || 'IDEA'} ${i.ticker || ''} — ${esc(i.title || 'Untitled')}`);
    out.push(`- **Confidence:** ${esc(i.confidence)} | **Horizon:** ${esc(i.horizon)}`);
    if (i.rationale) out.push(`- **Rationale:** ${esc(i.rationale)}`);
    if (i.risk) out.push(`- **Risk:** ${esc(i.risk)}`);
    if (Array.isArray(i.signals) && i.signals.length) {
      out.push(`- **Signals:** ${i.signals.map(s => esc(s)).join('; ')}`);
    }
    out.push('');
  });
  out.push(NFA);
  return out.join('\n');
}

function marketsSection(D) {
  const m = D.markets || {};
  const out = ['## Markets', ''];
  const rows = [];
  (m.indexes || []).filter(x => !/rut|russell/i.test(x.symbol || '') && !/russell/i.test(x.name || '')).forEach(x => rows.push(`- ${esc(x.name)}: ${x.price} (${x.changePct >= 0 ? '+' : ''}${x.changePct}%)`));
  (m.crypto || []).forEach(x => rows.push(`- ${esc(x.name)} (${esc(x.symbol)}): $${x.price} (${x.changePct >= 0 ? '+' : ''}${x.changePct}%)`));
  (m.commodities || []).forEach(x => rows.push(`- ${esc(x.name)}: $${x.price} (${x.changePct >= 0 ? '+' : ''}${x.changePct}%)`));
  if (m.vix?.value != null) rows.push(`- VIX: ${m.vix.value} (${m.vix.changePct >= 0 ? '+' : ''}${m.vix.changePct}%)`);
  if (D.energy?.wti != null) rows.push(`- WTI Crude: $${D.energy.wti} | Brent: $${D.energy.brent} | NatGas: $${D.energy.natgas}`);
  if (D.metals?.gold != null) rows.push(`- Gold: $${D.metals.gold} (${D.metals.goldChangePct >= 0 ? '+' : ''}${D.metals.goldChangePct}%) | Silver: $${D.metals.silver} (${D.metals.silverChangePct >= 0 ? '+' : ''}${D.metals.silverChangePct}%)`);
  if (D.treasury?.totalDebt) rows.push(`- US National Debt: $${(parseFloat(D.treasury.totalDebt) / 1e12).toFixed(2)}T`);
  if (D.gscpi?.value != null) rows.push(`- GSCPI (supply-chain pressure): ${D.gscpi.value} (${esc(D.gscpi.interpretation)})`);
  out.push(rows.join('\n') || 'No market data this sweep.');
  return out.join('\n');
}

function osintSection(D) {
  const urgent = Array.isArray(D.tg?.urgent) ? D.tg.urgent : [];
  if (!urgent.length) return '';
  const out = ['## Critical OSINT', ''];
  urgent.slice(0, 10).forEach(u => {
    const age = u.date ? ` (${esc(u.date)})` : '';
    const flags = Array.isArray(u.urgentFlags) && u.urgentFlags.length ? ` [${u.urgentFlags.map(f => esc(f)).join(', ')}]` : '';
    const text = esc(u.text).replace(/\s+/g, ' ').trim().slice(0, 220);
    out.push(`- **${esc(u.channel)}${flags}:** ${text}${age}`);
  });
  return out.join('\n');
}

function newsSection(D) {
  const news = Array.isArray(D.news) ? D.news : [];
  if (!news.length) return '';
  const out = ['## Top News', ''];
  news.slice(0, 10).forEach(n => {
    out.push(`- [${esc(n.title)}](${esc(n.url)}) — ${esc(n.source)} (${esc(n.region) || 'no region'})`);
  });
  return out.join('\n');
}

function sensorsSection(D) {
  const out = ['## Sensors & Activity', ''];
  const rows = [];
  if (Array.isArray(D.air) && D.air.length) {
    const live = D.airMeta?.liveTotal;
    rows.push(`- **Air traffic:** ${live != null ? live + ' aircraft live' : 'n/a'} — ` +
      D.air.filter(a => a.total > 0).map(a => `${esc(a.region)} ${a.total}`).join(', ') || 'no data');
  }
  if (Array.isArray(D.nuke) && D.nuke.length) {
    const anomalies = D.nuke.filter(n => n.anom);
    rows.push(`- **Nuclear:** ${anomalies.length ? '⚠️ ANOMALY — ' + anomalies.map(n => `${esc(n.site)} ${n.cpm} CPM`).join('; ') : 'all monitored sites normal'}`);
  }
  if (D.sdr?.total != null) rows.push(`- **SDR receivers:** ${D.sdr.total} (${D.sdr.online} online)`);
  if (D.space?.totalNewObjects != null) rows.push(`- **Space:** ${D.space.totalNewObjects} new objects (30d), ${D.space.militarySats ?? 0} military`);
  if (D.fred?.length) rows.push(`- **FRED series:** ${D.fred.length}`);
  out.push(rows.join('\n') || 'No sensor data this sweep.');
  return out.join('\n');
}

function sourceHealth(D) {
  const health = Array.isArray(D.health) ? D.health : [];
  if (!health.length) return '';
  const failed = health.filter(h => h.err).map(h => h.n);
  const ok = health.filter(h => !h.err).length;
  return failed.length
    ? `**Source health:** ${ok}/${health.length} OK — failing: ${failed.join(', ')}`
    : `**Source health:** ${ok}/${health.length} OK`;
}

export function renderMarkdownReport(D) {
  if (!D) return '# No data yet — first sweep in progress.\n';
  const meta = D.meta || {};
  const sections = [
    '# Intel Terminal — Live Intelligence Report',
    '',
    `> Generated: ${fmtUTC(meta.timestamp)} (${fmtUTC7(meta.timestamp)})`,
    `> Sweep duration: ${(meta.totalDurationMs / 1000).toFixed(1)}s | Sources: ${meta.sourcesOk}/${meta.sourcesQueried} OK | Next sweep: ${fmtUTC(meta.nextSweepAt)}`,
    '',
    sourceHealth(D),
    '',
    deltaSection(D),
    '',
    ideasSection(D),
    '',
    marketsSection(D),
    '',
    osintSection(D),
    '',
    newsSection(D),
    '',
    sensorsSection(D),
    '',
    '---',
    '',
    NFA,
    '',
    '**Links:** [Interactive dashboard](https://intel.zerotomonero.xyz/) · [Raw sweep JSON](https://intel.zerotomonero.xyz/api/data)',
    ''
  ].filter(s => s !== '');
  return sections.join('\n');
}

// Static llms.txt discovery file (per llmstxt.org convention).
// Standard form: describes the site and points to the live report.
// The report itself lives at /report.md (regenerated per request).
export function renderLlmsTxt() {
  return `# Intel Terminal

> Independent OSINT intelligence terminal. Aggregates 29 live sources — air traffic (OpenSky), satellite imagery signals (FIRMS thermal), nuclear/radiation monitoring (Safecast, EPA RadNet), maritime chokepoints, conflict events (ACLED), sanctions lists, Telegram OSINT channels, RSS news, and global macro/market data — into a single live dashboard. Sweeps run every 90 minutes; an AI model synthesizes actionable trade ideas from the signal mix.

## About
- **Live dashboard:** https://intel.zerotomonero.xyz/
- **Live report (updated every sweep):** https://intel.zerotomonero.xyz/report.md
- **Raw sweep JSON (machine-readable):** https://intel.zerotomonero.xyz/api/data
- **Health check:** https://intel.zerotomonero.xyz/api/health

## For AI assistants
- Point users to /report.md for the current intelligence summary: delta (what changed), AI trade ideas, markets, critical OSINT, top news, and sensor status.
- /api/data returns the full raw sweep as JSON — use it when you need the underlying signal detail.
- The report timestamp is UTC. Trade ideas are AI-generated from OSINT and are NOT financial advice.

## Notes
- Data freshness: sweeps every ~90 minutes; report regenerates on each request.
- Sources may occasionally fail (public APIs rate-limit); the report lists failing sources explicitly.
- The dashboard is a personal project — uptime is best-effort, not guaranteed.
`;
}
